import { Lead, DashboardMetrics } from '@/types'

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    empresa: 'Agro Minas Distribuidora',
    contato_nome: 'Cláudia Ramos',
    contato_cargo: 'Dir. Operações',
    telefone: '(31) 99999-1234',
    email: 'claudia@agrominas.com.br',
    cidade: 'Uberlândia',
    estado: 'MG',
    segmento: 'agronegocio',
    score_ia: 92,
    status: 'novo',
    fonte: 'linkedin',
    valor_estimado: 42000,
    responsavel_nome: 'Guilherme',
    responsavel_iniciais: 'GC',
    responsavel_cor: '#6366f1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '2',
    empresa: 'Têxtil Catarinense SA',
    contato_nome: 'Roberto Faria',
    contato_cargo: 'Gerente Compras',
    cidade: 'Blumenau',
    estado: 'SC',
    segmento: 'moda',
    score_ia: 74,
    status: 'novo',
    fonte: 'google',
    valor_estimado: 18000,
    responsavel_nome: 'Marina',
    responsavel_iniciais: 'MR',
    responsavel_cor: '#ec4899',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '3',
    empresa: 'Pharma Nordeste Ltda',
    contato_nome: 'Luíza Ferreira',
    contato_cargo: 'Suprimentos',
    cidade: 'Fortaleza',
    estado: 'CE',
    segmento: 'farmaceutico',
    score_ia: 81,
    status: 'novo',
    fonte: 'cnpj',
    valor_estimado: 25000,
    responsavel_nome: 'João',
    responsavel_iniciais: 'JS',
    responsavel_cor: '#10b981',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '4',
    empresa: 'Cerealista Planalto',
    contato_nome: 'Juliana Barros',
    contato_cargo: 'Dir. Logística',
    cidade: 'Rondonópolis',
    estado: 'MT',
    segmento: 'agronegocio',
    score_ia: 88,
    status: 'contactado',
    fonte: 'linkedin',
    valor_estimado: 18000,
    responsavel_nome: 'Guilherme',
    responsavel_iniciais: 'GC',
    responsavel_cor: '#6366f1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '5',
    empresa: 'Construtora Horizonte',
    contato_nome: 'Marcos Lima',
    contato_cargo: 'Dir. Compras',
    cidade: 'Belo Horizonte',
    estado: 'MG',
    segmento: 'construcao',
    score_ia: 67,
    status: 'contactado',
    fonte: 'cnpj',
    valor_estimado: 8000,
    responsavel_nome: 'Marina',
    responsavel_iniciais: 'MR',
    responsavel_cor: '#ec4899',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '6',
    empresa: 'Varejo Sul Atacado',
    contato_nome: 'Pedro Neto',
    contato_cargo: 'Dir. Logística',
    cidade: 'Porto Alegre',
    estado: 'RS',
    segmento: 'varejo',
    score_ia: 85,
    status: 'proposta',
    fonte: 'linkedin',
    valor_estimado: 42000,
    responsavel_nome: 'Guilherme',
    responsavel_iniciais: 'GC',
    responsavel_cor: '#6366f1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '7',
    empresa: 'Drogaria Vida e Saúde',
    contato_nome: 'Priscila Cunha',
    contato_cargo: 'Suprimentos',
    cidade: 'Goiânia',
    estado: 'GO',
    segmento: 'farmaceutico',
    score_ia: 69,
    status: 'proposta',
    fonte: 'cnpj',
    valor_estimado: 15000,
    responsavel_nome: 'João',
    responsavel_iniciais: 'JS',
    responsavel_cor: '#10b981',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '8',
    empresa: 'Grupo Fashion Brasil',
    contato_nome: 'Beatriz Costa',
    contato_cargo: 'CEO',
    cidade: 'São Paulo',
    estado: 'SP',
    segmento: 'moda',
    score_ia: 91,
    status: 'negociando',
    fonte: 'indicacao',
    valor_estimado: 56000,
    responsavel_nome: 'Guilherme',
    responsavel_iniciais: 'GC',
    responsavel_cor: '#6366f1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '9',
    empresa: 'Metalúrgica Nacional',
    contato_nome: 'Fernando Dias',
    contato_cargo: 'Dir. Compras',
    cidade: 'São Bernardo do Campo',
    estado: 'SP',
    segmento: 'industria',
    score_ia: 78,
    status: 'negociando',
    fonte: 'linkedin',
    valor_estimado: 28000,
    responsavel_nome: 'Marina',
    responsavel_iniciais: 'MR',
    responsavel_cor: '#ec4899',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '10',
    empresa: 'Farmácias Bem Estar',
    contato_nome: 'Isabela Moura',
    contato_cargo: 'Logística',
    cidade: 'Curitiba',
    estado: 'PR',
    segmento: 'farmaceutico',
    score_ia: 82,
    status: 'fechado',
    fonte: 'indicacao',
    valor_estimado: 7000,
    responsavel_nome: 'João',
    responsavel_iniciais: 'JS',
    responsavel_cor: '#10b981',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
  {
    id: '11',
    empresa: 'Supermercados Bom Preço',
    contato_nome: 'Carlos Mendes',
    contato_cargo: 'Dir. Logística',
    cidade: 'Fortaleza',
    estado: 'CE',
    segmento: 'varejo',
    score_ia: 75,
    status: 'fechado',
    fonte: 'linkedin',
    valor_estimado: 11000,
    responsavel_nome: 'Guilherme',
    responsavel_iniciais: 'GC',
    responsavel_cor: '#6366f1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tenant_id: 'tenant-1',
  },
]

export const MOCK_METRICS: DashboardMetrics = {
  leads_mes: 143,
  leads_delta: 18,
  valor_pipeline: 284000,
  oportunidades: 7,
  fechados_mes: 12,
  valor_fechado: 67000,
  taxa_conversao: 8.4,
  taxa_delta: -1.2,
}

export const KANBAN_COLUMNS = [
  { id: 'novo',        title: 'Novo Lead',    color: '#818cf8', dotColor: '#818cf8' },
  { id: 'contactado',  title: 'Contactado',   color: '#60a5fa', dotColor: '#60a5fa' },
  { id: 'proposta',    title: 'Proposta',     color: '#fbbf24', dotColor: '#f59e0b' },
  { id: 'negociando',  title: 'Negociando',   color: '#f472b6', dotColor: '#ec4899' },
  { id: 'fechado',     title: 'Fechado',      color: '#34d399', dotColor: '#10b981' },
] as const

export const LABEL_COLORS: Record<string, string> = {
  novo:       'linear-gradient(90deg, #6366f1, #a78bfa)',
  contactado: 'linear-gradient(90deg, #3b82f6, #60a5fa)',
  proposta:   'linear-gradient(90deg, #f59e0b, #fbbf24)',
  negociando: 'linear-gradient(90deg, #ec4899, #f472b6)',
  fechado:    'linear-gradient(90deg, #10b981, #34d399)',
}

export const SOURCE_LABELS: Record<string, { label: string; color: string; bg: string }> = {
  linkedin:  { label: 'LinkedIn',  color: '#818cf8', bg: 'rgba(99,102,241,0.15)'  },
  google:    { label: 'Google',    color: '#34d399', bg: 'rgba(16,185,129,0.15)'  },
  cnpj:      { label: 'CNPJ',      color: '#fbbf24', bg: 'rgba(245,158,11,0.15)'  },
  indicacao: { label: 'Indicação', color: '#c084fc', bg: 'rgba(192,132,252,0.15)' },
  apollo:    { label: 'Apollo',    color: '#60a5fa', bg: 'rgba(59,130,246,0.15)'  },
}

export const SEGMENT_LABELS: Record<string, string> = {
  agronegocio:  'Agronegócio',
  varejo:       'Varejo',
  industria:    'Indústria',
  farmaceutico: 'Farmacêutico',
  moda:         'Moda / Têxtil',
  construcao:   'Construção',
  alimentos:    'Alimentos',
  logistica:    'Logística',
  tecnologia:   'Tecnologia',
}
